### ISSUE TITLE
src/readdir.c: struct dirent -> d_type not available on sunos5

### ISSUE THREAD

**Issue by mgorny** [pkgcore/snakeoil#22]
Seems that the code has all necessary fallbacks for `DT_UNKNOWN` already. All that needs to be done is checking whether `d_type` is available, and `#ifdef`-ing all the non-fallback code to it.

**Comment by den4ix** [comment]
Checked this on SunOS-5.11, works nice now. Though there are still minor problems with pkgcore installation on solaris like:
diff --git a/ebd/ebuild.lib b/ebd/ebuild.lib
index 4124479..8f33656 100644
--- a/ebd/ebuild.lib
+++ b/ebd/ebuild.lib
@@ -21,7 +21,9 @@
 # readonly.  This limits users, but also helps to ensure that reloaded envs from older portages don't
 # overwrite an internal ebd.sh function that has since changed.

-ORIG_VARS=$(declare | grep -E '^[^[:space:]{}()]+=' | cut -s -d '=' -f 1)
+GREP='grep'
+[ `uname` == "SunOS" ] && GREP='/usr/xpg4/bin/grep' # grep with extended regex on Solaris
+ORIG_VARS=$(declare | ${GREP} -E '^[^[:space:]{}()]+=' | cut -s -d '=' -f 1)

**Comment by radhermit** [comment]
I switched this to just use compgen for now, thanks.
